###############################################################
# 本范例来源为网友
# 感谢网友 Ricky9w 私分享
# 新手用户专用版
###############################################################

mixed-port: 7890
#---------------------------------------------------#
## 配置文件需要放置在 $HOME/.config/clash/*.yaml
allow-lan: false
mode: Rule
# info / warning / error / debug / silent
log-level: info
external-controller: 127.0.0.1:9090

# https://github.com/Dreamacro/clash/wiki/Clash-Premium-Features#windows
# tun模式必须开sudo才能用,window可以安装scoop install sudo
# 还需要把wintun.dll放到配置目录,https://www.wintun.net
dns:
  enable: false
  enhanced-mode: fake-ip
  nameserver:
    - 114.114.114.114
    - 223.5.5.5
    - 8.8.8.8
  fallback:
    - 1.1.1.1
    - 8.8.4.4
  fake-ip-filter:
    - dns.msftncsi.com
    - www.msftncsi.com
    - www.msftconnecttest.com
tun:
  enable: false
  stack: gvisor
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - 198.18.0.2:53

proxies:

# 节点配置文件统一存放在 ./profiles/proxies/ 目录中
proxy-providers:
  gatern:
    type: http
    path: ./profiles/proxies/gatern.yaml
    url: https://example.com
    interval: 3600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  mojie:
    type: http
    path: ./profiles/proxies/mojie.yaml
    url: https://example.com
    interval: 3600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  xfltd:
    type: http
    path: ./profiles/proxies/xfltd.yaml
    url: https://example.com
    interval: 3600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  yy:
    type: http
    path: ./profiles/proxies/yy.yaml
    url: https://example.com
    interval: 3600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
  sf:
    type: http
    path: ./profiles/proxies/sf.yaml
    url: https://example.com
    interval: 3600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300

proxy-groups:
  - name: S-mode
    type: select
    proxies:
      - DIRECT
      - REJECT
      - A-all
      - S-gatern
      - S-mojie
      - S-xfltd
      - S-yy
      - S-sf
      - replit_xray_vmess
  - name: other
    type: select
    proxies:
      - DIRECT
      - REJECT
      - A-all
      - S-gatern
      - S-mojie
      - S-xfltd
      - S-yy
      - S-sf
      - replit_xray_vmess
  - name: A-all
    type: url-test
    interval: 3600
    url: http://www.gstatic.com/generate_204
    proxies:
      - A-gatern
      - A-mojie
      - A-xfltd
      - A-yy
      - A-sf
      - replit_xray_vmess
  - name: S-gatern
    type: select
    interval: 3600
    url: http://www.gstatic.com/generate_204
    proxies:
      - A-gatern
    use:
      - gatern
  - name: A-gatern
    type: url-test
    interval: 3600
    url: http://www.gstatic.com/generate_204
    use:
      - gatern

  - name: S-mojie
    type: select
    interval: 3600
    url: http://www.gstatic.com/generate_204
    proxies:
      - A-mojie
    use:
      - mojie
  - name: A-mojie
    type: url-test
    interval: 3600
    url: http://www.gstatic.com/generate_204
    use:
      - mojie

  - name: S-xfltd
    type: select
    interval: 3600
    url: http://www.gstatic.com/generate_204
    proxies:
      - A-xfltd
    use:
      - xfltd
  - name: A-xfltd
    type: url-test
    interval: 3600
    url: http://www.gstatic.com/generate_204
    use:
      - xfltd

  - name: S-yy
    type: select
    interval: 3600
    url: http://www.gstatic.com/generate_204
    proxies:
      - A-yy
    use:
      - yy
  - name: A-yy
    type: url-test
    interval: 3600
    url: http://www.gstatic.com/generate_204
    use:
      - yy

  - name: S-sf
    type: select
    interval: 3600
    url: http://www.gstatic.com/generate_204
    proxies:
      - A-sf
    use:
      - sf
  - name: A-sf
    type: url-test
    interval: 3600
    url: http://www.gstatic.com/generate_204
    use:
      - sf

rule-providers:
  # https://github.com/Loyalsoldier/clash-rules
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./profiles/rules/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./profiles/rules/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./profiles/rules/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./profiles/rules/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./profiles/rules/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./profiles/rules/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./profiles/rules/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./profiles/rules/gfw.yaml
    interval: 86400

  greatfire:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt"
    path: ./profiles/rules/greatfire.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./profiles/rules/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./profiles/rules/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./profiles/rules/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./profiles/rules/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./profiles/rules/applications.yaml
    interval: 86400

  # https://github.com/ACL4SSR/ACL4SSR/tree/master/Clash
  # ACL4SSR的规则碎片,没法直接使用,应该转换一下
  # BanAd:
  #   type: http
  #   behavior: classical
  #   url: "https://gcore.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/BanAD.list"
  #   path: ./profiles/ACL4SSR/BanAd.yaml
  #   interval: 86400

  # BanEasyList:
  #   type: http
  #   behavior: classical
  #   url: "https://gcore.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/BanEasyList.list"
  #   path: ./profiles/ACL4SSR/BanEasyList.yaml
  #   interval: 86400

  # BanEasyListChina:
  #   type: http
  #   behavior: classical
  #   url: "https://gcore.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/BanEasyListChina.list"
  #   path: ./profiles/ACL4SSR/BanEasyListChina.yaml
  #   interval: 86400

  # BanEasyPrivacy:
  #   type: http
  #   behavior: classical
  #   url: "https://gcore.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/BanEasyPrivacy.list"
  #   path: ./profiles/ACL4SSR/BanEasyPrivacy.yaml
  #   interval: 86400

  # BanProgramAD:
  #   type: http
  #   behavior: classical
  #   url: "https://gcore.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/BanProgramAD.list"
  #   path: ./profiles/ACL4SSR/BanProgramAD.yaml
  #   interval: 86400

  # https://github.com/privacy-protection-tools/anti-AD
  anti-ad:
    type: http
    behavior: domain
    url: "https://anti-ad.net/clash.yaml"
    path: ./profiles/anti-ad/anti-ad.yaml
    interval: 86400

# 黑名单模式，意为「只有命中规则的网络流量，才使用代理」
rules:
  - RULE-SET,anti-ad,REJECT
  # - RULE-SET,BanAd,REJECT
  # - RULE-SET,BanEasyList,REJECT
  # - RULE-SET,BanEasyListChina,REJECT
  # - RULE-SET,BanEasyPrivacy,REJECT
  # - RULE-SET,BanProgramAD,REJECT
  # - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,tld-not-cn,S-mode
  - RULE-SET,gfw,S-mode
  - RULE-SET,greatfire,S-mode
  - RULE-SET,telegramcidr,S-mode
  - MATCH,other
# 白名单模式，意为「没有命中规则的网络流量，统统使用代理」
# rules:
#   - RULE-SET,applications,DIRECT
#   - DOMAIN,clash.razord.top,DIRECT
#   - DOMAIN,yacd.haishan.me,DIRECT
#   - RULE-SET,private,DIRECT
#   - RULE-SET,reject,REJECT
#   - RULE-SET,icloud,DIRECT
#   - RULE-SET,apple,DIRECT
#   - RULE-SET,google,DIRECT
#   - RULE-SET,proxy,PROXY
#   - RULE-SET,direct,DIRECT
#   - RULE-SET,lancidr,DIRECT
#   - RULE-SET,cncidr,DIRECT
#   - RULE-SET,telegramcidr,PROXY
#   - GEOIP,LAN,DIRECT
#   - GEOIP,CN,DIRECT
#   - MATCH,PROXY
